# Generated by Django 4.2.30 on 2026-06-13 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delivrance', models.DateTimeField(auto_now_add=True)),
                ('code_verification', models.CharField(blank=True, max_length=50, unique=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('etudiant', models.ForeignKey(limit_choices_to={'profile__role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
