# Generated by Django 4.2.30 on 2026-06-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='support_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cours_pdf/'),
        ),
    ]
